- name: Deploy `gouv.fa`/`farer.group`
  hosts: farer-web

  vars:
    - SRCROOT= "/srv/srcs/gouv.fa"
    - PUBWEBROOT= "/srv/farer.group"
    - WEBROOT= "/srv/gouv.fa"
    - ZOLA_VERSION= "0.16.1"

  pre_tasks:
    - name: Confirm server uses AARCH64, X86_64, or ARM

  tasks:
    - name: Install Zola
      block:
        - name: Download Zola binary
          become: false
          ansible.builtin.get_url:
            url: "http://pkgs.gouv.fa/zola/{{ZOLA_VERSION}}/{{arch}}"
            dest: "/tmp/zola_{{ZOLA_VERSION}}_{{arch}}"
          register: _download_bin
          until: _download_bin is succeeded
          retries: 5
          delay: 2
          check_mode: false
        - name: Install Zola binary
          ansible.builtin.copy:
            src: "/tmp/zola_{{ZOLA_VERSION}}_{{arch}}"
            dest: "/usr/bin/zola"
            owner: root
            group: root
            mode: 0750
            remote_src: yes
          when: not ansible_check_mode
    - name: Send site to server
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: {{SRCROOT}}
        owner: caddy
        group: caddy
        mode: 0750
      with_fileglob:
        - content/
        - sass/
        - static/
        - templates/
        - Caddyfile
        - config.toml
        - directory.json

    - name: Build site as `farer.group`
      ansible.builtin.shell: /usr/bin/zola -o {{PUBWEBROOT}} -u https://farer.group
      when: invetory_hostname in groups['PUB-farer-web']
    - name: Build site as `gouv.fa`
      ansible.builtin.shell: /usr/bin/zola -o {{PUBWEBROOT}} -u https://farer.group
      when: invetory_hostname not in groups['PUB-farer-web']
      