# The URL the site will be built for
base_url = "https://gouv.fa"
title= "Gouv.fa"

default_language= "en"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[search]
include_title= true
include_content= true

# i18n
[languages.en]
	build_search_index= true
[languages.en.translations]
	searchtitle= "Search"
	newstitle= "News"

	searchlabel= "Search pages"

	help= "Help"
	contact= "Contact"
	copyright= "Some rights reserved."
	lastupdated= "Last updated"

	tag_farer= "Official service"
	tag_farer_desc= "This service is run by The Farer Group."
	tag_staff= "Staff-operated"
	tag_staff_desc= "This service is run by a staff member from The Farer Group."
	tag_restricted= "Restricted"
	tag_restricted_desc= "This service isn't open to all Farer members, Farer visitors, or is intended for a certain group of people."
	tag_certified= "Certified"
	tag_certified_desc= "This service has been certified to be compliant with Farer policies. A report of such can be found via FarerNIC."

	form-name= "What are your given names?"
	form-surnom= "What is your surname?"
	form-email= "What is your Farer-issued email address?"
	form-memberid= "What is your member ID?"

	form-address= "What is your mailing address?"
	form-address-street= "Postal address"
	form-address-addt= "Supplemental informations"
	form-address-city= "City"
	form-address-postal= "Postal code"
	form-address-country= "Country"

	form-requireddocs= "Be sure to include the following documents in your request:"
	form-proofofmembership= "Proof of Farer membeship"

[languages.fr]
	build_search_index= true
[languages.fr.translations]
	searchtitle= "Rechercher"
	newstitle= "Actualités"

	searchlabel= "Rechercher les pages"

	help= "Obtenez de l'aide"
	contact= "Contactez-nous"
	copyright= "Certains droits réservés."
	lastupdated= "Mis à jour"

	tag_farer= "Service officiel"
	tag_farer_desc= "Ce service est assuré par The Farer Group."
	tag_staff= "Géré par le personnel Farer"
	tag_staff_desc= "Ce service est géré par un membre du personnel de The Farer Group."
	tag_restricted= "Accès limité"
	tag_restricted_desc= "Ce service n’est pas disponible pour tous les membres de Farer, les visiteurs de Farer, ou est destiné à un certain groupe de personnes."
	tag_certified= "Certifié"
	tag_certified_desc= "Ce service a été certifié conforme aux politiques Farer. Un rapport à ce sujet peut être trouvé via FarerNIC."

	form-name= "Quels sont vos prénoms?"
	form-surnom= "Quel est votre nom de famille?"
	form-email= "Quell est votre e-mail émise par Farer?"
	form-memberid= "Quel est votre numéro de ID émise par Farer?"

	form-address= "Quelle est votre adresse postale?"
	form-address-street= "Adresse postale"
	form-address-addt= "Informations supplémentaires"
	form-address-city= "Ville"
	form-address-postal= "Code d'postal"
	form-address-country= "Pays"

	form-requireddocs= "Assurez-vous d'inclure les documents suivants dans votre demande:"
	form-proofofmembership= "Preuve d’adhésion à Farer"

#[extra]
#unofficial= []
