# The URL the site will be built for
base_url = "https://wiki.lleb"

default_language= "en"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[search]
include_title= true
include_content= true

# i18n
[languages.en]
build_search_index= true
[languages.es]
build_search_index= true
[languages.fr]
build_search_index= true

# i18n (unofficial)
[languages.ri]
build_search_index= false
[languages.ri.translations]
notice= "Rishi Dialect is not an official language in the LLEB community. This translation is provided for information purposes only and is provided to the community by the community."

[extra]
unofficial= ["ri"]