# The URL the site will be built for
base_url = "https://gouv.fa"
title= "Gouv.fa"

default_language= "en"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[search]
include_title= true
include_content= true

# i18n
[languages.en]
	build_search_index= true
[languages.en.translations]
	curlang= "Current locale."
	notrans= "No translation available."
	searchtitle= "Search"
	directorytitle= "Directory"
	pubserv= "Farer Public Services"
	help= "Help"
	contact= "Contact"
	copyright= "Some rights reserved."

[languages.fr]
	build_search_index= true
[languages.fr.translations]
	curlang= "Langue actuel."
	notrans= "Pas translation."
	searchtitle= "Rechercher"
	directorytitle= "Annuaire"
	pubserv= "Services publiques Farer"
	topofpage= "Haut de page."
	help= "Obtenez de l'aide"
	contact= "Contactez-nous"
	copyright= "Certains droits réservés."

#[extra]
#unofficial= []
