# The URL the site will be built for
base_url = "https://gouv.fa"
title= "Gouv.fa"

default_language= "en"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = false
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true

[search]
include_title= true
include_content= true

# i18n
[languages.en]
	build_search_index= true
[languages.en.translations]
	curlang= "Current locale."
	notrans= "No translation available."
	searchtitle= "search"
	pubserv= "Farer Public Services"
	topofpage= "Top of page."
	copyright= "Some rights reserved."

[languages.fr]
	build_search_index= true
[languages.fr.translations]
	curlang= "Langue actuel."
	notrans= "Pas translation."
	searchtitle= "rechercher"
	pubserv= "Services publiques Farer"
	topofpage= "Haut de page."
	copyright= "Certains droits réservés."

#[languages.es]
#build_search_index= true

# i18n (unofficial)
#[languages.ri]
#build_search_index= false
#[languages.ri.translations]
#notice= "Rishi Dialect is not an official language. This translation is provided for information purposes only and is provided to the community by the community."

#[extra]
#unofficial= []
